// Out-of-process plugin contract (DESIGN.md §2).
//
// A plugin process implements one or more of these services and is reached
// over Unix-domain or TCP gRPC. The lwauth core wraps each remote call in
// the pkg/module Identifier/Authorizer/ResponseMutator interface so the
// pipeline cannot tell built-ins from plugins apart.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lightweightauth/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentifierPlugin_Identify_FullMethodName = "/lightweightauth.plugin.v1.IdentifierPlugin/Identify"
)

// IdentifierPluginClient is the client API for IdentifierPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentifierPluginClient interface {
	Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error)
}

type identifierPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentifierPluginClient(cc grpc.ClientConnInterface) IdentifierPluginClient {
	return &identifierPluginClient{cc}
}

func (c *identifierPluginClient) Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifyResponse)
	err := c.cc.Invoke(ctx, IdentifierPlugin_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentifierPluginServer is the server API for IdentifierPlugin service.
// All implementations should embed UnimplementedIdentifierPluginServer
// for forward compatibility.
type IdentifierPluginServer interface {
	Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error)
}

// UnimplementedIdentifierPluginServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentifierPluginServer struct{}

func (UnimplementedIdentifierPluginServer) Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedIdentifierPluginServer) testEmbeddedByValue() {}

// UnsafeIdentifierPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentifierPluginServer will
// result in compilation errors.
type UnsafeIdentifierPluginServer interface {
	mustEmbedUnimplementedIdentifierPluginServer()
}

func RegisterIdentifierPluginServer(s grpc.ServiceRegistrar, srv IdentifierPluginServer) {
	// If the following call panics, it indicates UnimplementedIdentifierPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentifierPlugin_ServiceDesc, srv)
}

func _IdentifierPlugin_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifierPluginServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentifierPlugin_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifierPluginServer).Identify(ctx, req.(*IdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentifierPlugin_ServiceDesc is the grpc.ServiceDesc for IdentifierPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentifierPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightweightauth.plugin.v1.IdentifierPlugin",
	HandlerType: (*IdentifierPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _IdentifierPlugin_Identify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lightweightauth/plugin/v1/plugin.proto",
}

const (
	AuthorizerPlugin_Authorize_FullMethodName = "/lightweightauth.plugin.v1.AuthorizerPlugin/Authorize"
)

// AuthorizerPluginClient is the client API for AuthorizerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizerPluginClient interface {
	Authorize(ctx context.Context, in *AuthorizePluginRequest, opts ...grpc.CallOption) (*AuthorizePluginResponse, error)
}

type authorizerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizerPluginClient(cc grpc.ClientConnInterface) AuthorizerPluginClient {
	return &authorizerPluginClient{cc}
}

func (c *authorizerPluginClient) Authorize(ctx context.Context, in *AuthorizePluginRequest, opts ...grpc.CallOption) (*AuthorizePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizePluginResponse)
	err := c.cc.Invoke(ctx, AuthorizerPlugin_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizerPluginServer is the server API for AuthorizerPlugin service.
// All implementations should embed UnimplementedAuthorizerPluginServer
// for forward compatibility.
type AuthorizerPluginServer interface {
	Authorize(context.Context, *AuthorizePluginRequest) (*AuthorizePluginResponse, error)
}

// UnimplementedAuthorizerPluginServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizerPluginServer struct{}

func (UnimplementedAuthorizerPluginServer) Authorize(context.Context, *AuthorizePluginRequest) (*AuthorizePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAuthorizerPluginServer) testEmbeddedByValue() {}

// UnsafeAuthorizerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizerPluginServer will
// result in compilation errors.
type UnsafeAuthorizerPluginServer interface {
	mustEmbedUnimplementedAuthorizerPluginServer()
}

func RegisterAuthorizerPluginServer(s grpc.ServiceRegistrar, srv AuthorizerPluginServer) {
	// If the following call panics, it indicates UnimplementedAuthorizerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizerPlugin_ServiceDesc, srv)
}

func _AuthorizerPlugin_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerPluginServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerPlugin_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerPluginServer).Authorize(ctx, req.(*AuthorizePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizerPlugin_ServiceDesc is the grpc.ServiceDesc for AuthorizerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightweightauth.plugin.v1.AuthorizerPlugin",
	HandlerType: (*AuthorizerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _AuthorizerPlugin_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lightweightauth/plugin/v1/plugin.proto",
}

const (
	MutatorPlugin_Mutate_FullMethodName = "/lightweightauth.plugin.v1.MutatorPlugin/Mutate"
)

// MutatorPluginClient is the client API for MutatorPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutatorPluginClient interface {
	Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutateResponse, error)
}

type mutatorPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewMutatorPluginClient(cc grpc.ClientConnInterface) MutatorPluginClient {
	return &mutatorPluginClient{cc}
}

func (c *mutatorPluginClient) Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateResponse)
	err := c.cc.Invoke(ctx, MutatorPlugin_Mutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutatorPluginServer is the server API for MutatorPlugin service.
// All implementations should embed UnimplementedMutatorPluginServer
// for forward compatibility.
type MutatorPluginServer interface {
	Mutate(context.Context, *MutateRequest) (*MutateResponse, error)
}

// UnimplementedMutatorPluginServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutatorPluginServer struct{}

func (UnimplementedMutatorPluginServer) Mutate(context.Context, *MutateRequest) (*MutateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mutate not implemented")
}
func (UnimplementedMutatorPluginServer) testEmbeddedByValue() {}

// UnsafeMutatorPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutatorPluginServer will
// result in compilation errors.
type UnsafeMutatorPluginServer interface {
	mustEmbedUnimplementedMutatorPluginServer()
}

func RegisterMutatorPluginServer(s grpc.ServiceRegistrar, srv MutatorPluginServer) {
	// If the following call panics, it indicates UnimplementedMutatorPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MutatorPlugin_ServiceDesc, srv)
}

func _MutatorPlugin_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutatorPluginServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutatorPlugin_Mutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutatorPluginServer).Mutate(ctx, req.(*MutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MutatorPlugin_ServiceDesc is the grpc.ServiceDesc for MutatorPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutatorPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightweightauth.plugin.v1.MutatorPlugin",
	HandlerType: (*MutatorPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mutate",
			Handler:    _MutatorPlugin_Mutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lightweightauth/plugin/v1/plugin.proto",
}
