// Out-of-process plugin contract (DESIGN.md §2).
//
// A plugin process implements one or more of these services and is reached
// over Unix-domain or TCP gRPC. The lwauth core wraps each remote call in
// the pkg/module Identifier/Authorizer/ResponseMutator interface so the
// pipeline cannot tell built-ins from plugins apart.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lightweightauth/plugin/v1/plugin.proto

package pluginv1

import (
	v1 "github.com/mikeappsec/lightweightauth/api/proto/lightweightauth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *v1.AuthorizeRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyRequest) GetRequest() *v1.AuthorizeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type IdentifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// no_match=true means "not my credential"; the host moves to the next
	// identifier. Mutually exclusive with identity.
	NoMatch       bool         `protobuf:"varint,1,opt,name=no_match,json=noMatch,proto3" json:"no_match,omitempty"`
	Identity      *v1.Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Error         string       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyResponse) GetNoMatch() bool {
	if x != nil {
		return x.NoMatch
	}
	return false
}

func (x *IdentifyResponse) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *IdentifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuthorizePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *v1.AuthorizeRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Identity      *v1.Identity           `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePluginRequest) Reset() {
	*x = AuthorizePluginRequest{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePluginRequest) ProtoMessage() {}

func (x *AuthorizePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePluginRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePluginRequest) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizePluginRequest) GetRequest() *v1.AuthorizeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthorizePluginRequest) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type AuthorizePluginResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allow           bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	HttpStatus      int32                  `protobuf:"varint,2,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	UpstreamHeaders map[string]string      `protobuf:"bytes,3,rep,name=upstream_headers,json=upstreamHeaders,proto3" json:"upstream_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseHeaders map[string]string      `protobuf:"bytes,4,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DenyReason      string                 `protobuf:"bytes,5,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizePluginResponse) Reset() {
	*x = AuthorizePluginResponse{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePluginResponse) ProtoMessage() {}

func (x *AuthorizePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePluginResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePluginResponse) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizePluginResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *AuthorizePluginResponse) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *AuthorizePluginResponse) GetUpstreamHeaders() map[string]string {
	if x != nil {
		return x.UpstreamHeaders
	}
	return nil
}

func (x *AuthorizePluginResponse) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *AuthorizePluginResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *AuthorizePluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MutateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *v1.AuthorizeRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Identity      *v1.Identity           `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Decision      *v1.AuthorizeResponse  `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *MutateRequest) GetRequest() *v1.AuthorizeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MutateRequest) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *MutateRequest) GetDecision() *v1.AuthorizeResponse {
	if x != nil {
		return x.Decision
	}
	return nil
}

type MutateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpstreamHeaders map[string]string      `protobuf:"bytes,1,rep,name=upstream_headers,json=upstreamHeaders,proto3" json:"upstream_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseHeaders map[string]string      `protobuf:"bytes,2,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutateResponse) Reset() {
	*x = MutateResponse{}
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateResponse) ProtoMessage() {}

func (x *MutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateResponse.ProtoReflect.Descriptor instead.
func (*MutateResponse) Descriptor() ([]byte, []int) {
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *MutateResponse) GetUpstreamHeaders() map[string]string {
	if x != nil {
		return x.UpstreamHeaders
	}
	return nil
}

func (x *MutateResponse) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *MutateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lightweightauth_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_lightweightauth_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"&lightweightauth/plugin/v1/plugin.proto\x12\x19lightweightauth.plugin.v1\x1a\x1dlightweightauth/v1/auth.proto\"Q\n" +
	"\x0fIdentifyRequest\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.lightweightauth.v1.AuthorizeRequestR\arequest\"}\n" +
	"\x10IdentifyResponse\x12\x19\n" +
	"\bno_match\x18\x01 \x01(\bR\anoMatch\x128\n" +
	"\bidentity\x18\x02 \x01(\v2\x1c.lightweightauth.v1.IdentityR\bidentity\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x16AuthorizePluginRequest\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.lightweightauth.v1.AuthorizeRequestR\arequest\x128\n" +
	"\bidentity\x18\x02 \x01(\v2\x1c.lightweightauth.v1.IdentityR\bidentity\"\xf7\x03\n" +
	"\x17AuthorizePluginResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x1f\n" +
	"\vhttp_status\x18\x02 \x01(\x05R\n" +
	"httpStatus\x12r\n" +
	"\x10upstream_headers\x18\x03 \x03(\v2G.lightweightauth.plugin.v1.AuthorizePluginResponse.UpstreamHeadersEntryR\x0fupstreamHeaders\x12r\n" +
	"\x10response_headers\x18\x04 \x03(\v2G.lightweightauth.plugin.v1.AuthorizePluginResponse.ResponseHeadersEntryR\x0fresponseHeaders\x12\x1f\n" +
	"\vdeny_reason\x18\x05 \x01(\tR\n" +
	"denyReason\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x1aB\n" +
	"\x14UpstreamHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\rMutateRequest\x12>\n" +
	"\arequest\x18\x01 \x01(\v2$.lightweightauth.v1.AuthorizeRequestR\arequest\x128\n" +
	"\bidentity\x18\x02 \x01(\v2\x1c.lightweightauth.v1.IdentityR\bidentity\x12A\n" +
	"\bdecision\x18\x03 \x01(\v2%.lightweightauth.v1.AuthorizeResponseR\bdecision\"\x84\x03\n" +
	"\x0eMutateResponse\x12i\n" +
	"\x10upstream_headers\x18\x01 \x03(\v2>.lightweightauth.plugin.v1.MutateResponse.UpstreamHeadersEntryR\x0fupstreamHeaders\x12i\n" +
	"\x10response_headers\x18\x02 \x03(\v2>.lightweightauth.plugin.v1.MutateResponse.ResponseHeadersEntryR\x0fresponseHeaders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1aB\n" +
	"\x14UpstreamHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012w\n" +
	"\x10IdentifierPlugin\x12c\n" +
	"\bIdentify\x12*.lightweightauth.plugin.v1.IdentifyRequest\x1a+.lightweightauth.plugin.v1.IdentifyResponse2\x86\x01\n" +
	"\x10AuthorizerPlugin\x12r\n" +
	"\tAuthorize\x121.lightweightauth.plugin.v1.AuthorizePluginRequest\x1a2.lightweightauth.plugin.v1.AuthorizePluginResponse2n\n" +
	"\rMutatorPlugin\x12]\n" +
	"\x06Mutate\x12(.lightweightauth.plugin.v1.MutateRequest\x1a).lightweightauth.plugin.v1.MutateResponseBTZRgithub.com/mikeappsec/lightweightauth/api/proto/lightweightauth/plugin/v1;pluginv1b\x06proto3"

var (
	file_lightweightauth_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_lightweightauth_plugin_v1_plugin_proto_rawDescData []byte
)

func file_lightweightauth_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_lightweightauth_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_lightweightauth_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightweightauth_plugin_v1_plugin_proto_rawDesc), len(file_lightweightauth_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_lightweightauth_plugin_v1_plugin_proto_rawDescData
}

var file_lightweightauth_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lightweightauth_plugin_v1_plugin_proto_goTypes = []any{
	(*IdentifyRequest)(nil),         // 0: lightweightauth.plugin.v1.IdentifyRequest
	(*IdentifyResponse)(nil),        // 1: lightweightauth.plugin.v1.IdentifyResponse
	(*AuthorizePluginRequest)(nil),  // 2: lightweightauth.plugin.v1.AuthorizePluginRequest
	(*AuthorizePluginResponse)(nil), // 3: lightweightauth.plugin.v1.AuthorizePluginResponse
	(*MutateRequest)(nil),           // 4: lightweightauth.plugin.v1.MutateRequest
	(*MutateResponse)(nil),          // 5: lightweightauth.plugin.v1.MutateResponse
	nil,                             // 6: lightweightauth.plugin.v1.AuthorizePluginResponse.UpstreamHeadersEntry
	nil,                             // 7: lightweightauth.plugin.v1.AuthorizePluginResponse.ResponseHeadersEntry
	nil,                             // 8: lightweightauth.plugin.v1.MutateResponse.UpstreamHeadersEntry
	nil,                             // 9: lightweightauth.plugin.v1.MutateResponse.ResponseHeadersEntry
	(*v1.AuthorizeRequest)(nil),     // 10: lightweightauth.v1.AuthorizeRequest
	(*v1.Identity)(nil),             // 11: lightweightauth.v1.Identity
	(*v1.AuthorizeResponse)(nil),    // 12: lightweightauth.v1.AuthorizeResponse
}
var file_lightweightauth_plugin_v1_plugin_proto_depIdxs = []int32{
	10, // 0: lightweightauth.plugin.v1.IdentifyRequest.request:type_name -> lightweightauth.v1.AuthorizeRequest
	11, // 1: lightweightauth.plugin.v1.IdentifyResponse.identity:type_name -> lightweightauth.v1.Identity
	10, // 2: lightweightauth.plugin.v1.AuthorizePluginRequest.request:type_name -> lightweightauth.v1.AuthorizeRequest
	11, // 3: lightweightauth.plugin.v1.AuthorizePluginRequest.identity:type_name -> lightweightauth.v1.Identity
	6,  // 4: lightweightauth.plugin.v1.AuthorizePluginResponse.upstream_headers:type_name -> lightweightauth.plugin.v1.AuthorizePluginResponse.UpstreamHeadersEntry
	7,  // 5: lightweightauth.plugin.v1.AuthorizePluginResponse.response_headers:type_name -> lightweightauth.plugin.v1.AuthorizePluginResponse.ResponseHeadersEntry
	10, // 6: lightweightauth.plugin.v1.MutateRequest.request:type_name -> lightweightauth.v1.AuthorizeRequest
	11, // 7: lightweightauth.plugin.v1.MutateRequest.identity:type_name -> lightweightauth.v1.Identity
	12, // 8: lightweightauth.plugin.v1.MutateRequest.decision:type_name -> lightweightauth.v1.AuthorizeResponse
	8,  // 9: lightweightauth.plugin.v1.MutateResponse.upstream_headers:type_name -> lightweightauth.plugin.v1.MutateResponse.UpstreamHeadersEntry
	9,  // 10: lightweightauth.plugin.v1.MutateResponse.response_headers:type_name -> lightweightauth.plugin.v1.MutateResponse.ResponseHeadersEntry
	0,  // 11: lightweightauth.plugin.v1.IdentifierPlugin.Identify:input_type -> lightweightauth.plugin.v1.IdentifyRequest
	2,  // 12: lightweightauth.plugin.v1.AuthorizerPlugin.Authorize:input_type -> lightweightauth.plugin.v1.AuthorizePluginRequest
	4,  // 13: lightweightauth.plugin.v1.MutatorPlugin.Mutate:input_type -> lightweightauth.plugin.v1.MutateRequest
	1,  // 14: lightweightauth.plugin.v1.IdentifierPlugin.Identify:output_type -> lightweightauth.plugin.v1.IdentifyResponse
	3,  // 15: lightweightauth.plugin.v1.AuthorizerPlugin.Authorize:output_type -> lightweightauth.plugin.v1.AuthorizePluginResponse
	5,  // 16: lightweightauth.plugin.v1.MutatorPlugin.Mutate:output_type -> lightweightauth.plugin.v1.MutateResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lightweightauth_plugin_v1_plugin_proto_init() }
func file_lightweightauth_plugin_v1_plugin_proto_init() {
	if File_lightweightauth_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightweightauth_plugin_v1_plugin_proto_rawDesc), len(file_lightweightauth_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_lightweightauth_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_lightweightauth_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_lightweightauth_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_lightweightauth_plugin_v1_plugin_proto = out.File
	file_lightweightauth_plugin_v1_plugin_proto_goTypes = nil
	file_lightweightauth_plugin_v1_plugin_proto_depIdxs = nil
}
