// Native LightweightAuth gRPC API (Door B in DESIGN.md §1).
//
// This file is the design source of truth for the native authorization
// surface. Code is generated with buf in milestone M2; until then the
// shape is committed here for review.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lightweightauth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`     // "GET", "grpc.health.v1.Health/Check", ...
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // free-form: URL path, gRPC FQN, topic name, ...
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // optional, opt-in per AuthConfig
	Peer          *PeerInfo              `protobuf:"bytes,5,opt,name=peer,proto3" json:"peer,omitempty"` // mTLS chain, IP, SPIFFE ID
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,7,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // trace id, request id, ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AuthorizeRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AuthorizeRequest) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *AuthorizeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthorizeRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteAddr    string                 `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	SpiffeId      string                 `protobuf:"bytes,2,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *PeerInfo) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                                                           // identifier name that produced it
	Claims        map[string]string      `protobuf:"bytes,3,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // flattened claims (numbers/objects -> JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Identity) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

type AuthorizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allow           bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	HttpStatus      int32                  `protobuf:"varint,2,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"` // hint for HTTP callers
	UpstreamHeaders map[string]string      `protobuf:"bytes,3,rep,name=upstream_headers,json=upstreamHeaders,proto3" json:"upstream_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseHeaders map[string]string      `protobuf:"bytes,4,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Identity        *Identity              `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	DenyReason      string                 `protobuf:"bytes,6,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *AuthorizeResponse) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *AuthorizeResponse) GetUpstreamHeaders() map[string]string {
	if x != nil {
		return x.UpstreamHeaders
	}
	return nil
}

func (x *AuthorizeResponse) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *AuthorizeResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AuthorizeResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

var File_lightweightauth_v1_auth_proto protoreflect.FileDescriptor

const file_lightweightauth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1dlightweightauth/v1/auth.proto\x12\x12lightweightauth.v1\"\xbb\x03\n" +
	"\x10AuthorizeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12K\n" +
	"\aheaders\x18\x03 \x03(\v21.lightweightauth.v1.AuthorizeRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x120\n" +
	"\x04peer\x18\x05 \x01(\v2\x1c.lightweightauth.v1.PeerInfoR\x04peer\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12K\n" +
	"\acontext\x18\a \x03(\v21.lightweightauth.v1.AuthorizeRequest.ContextEntryR\acontext\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\bPeerInfo\x12\x1f\n" +
	"\vremote_addr\x18\x01 \x01(\tR\n" +
	"remoteAddr\x12\x1b\n" +
	"\tspiffe_id\x18\x02 \x01(\tR\bspiffeIdJ\x04\b\x03\x10\x04R\n" +
	"cert_chain\"\xb9\x01\n" +
	"\bIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12@\n" +
	"\x06claims\x18\x03 \x03(\v2(.lightweightauth.v1.Identity.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x03\n" +
	"\x11AuthorizeResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x1f\n" +
	"\vhttp_status\x18\x02 \x01(\x05R\n" +
	"httpStatus\x12e\n" +
	"\x10upstream_headers\x18\x03 \x03(\v2:.lightweightauth.v1.AuthorizeResponse.UpstreamHeadersEntryR\x0fupstreamHeaders\x12e\n" +
	"\x10response_headers\x18\x04 \x03(\v2:.lightweightauth.v1.AuthorizeResponse.ResponseHeadersEntryR\x0fresponseHeaders\x128\n" +
	"\bidentity\x18\x05 \x01(\v2\x1c.lightweightauth.v1.IdentityR\bidentity\x12\x1f\n" +
	"\vdeny_reason\x18\x06 \x01(\tR\n" +
	"denyReason\x1aB\n" +
	"\x14UpstreamHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc4\x01\n" +
	"\x04Auth\x12X\n" +
	"\tAuthorize\x12$.lightweightauth.v1.AuthorizeRequest\x1a%.lightweightauth.v1.AuthorizeResponse\x12b\n" +
	"\x0fAuthorizeStream\x12$.lightweightauth.v1.AuthorizeRequest\x1a%.lightweightauth.v1.AuthorizeResponse(\x010\x01BKZIgithub.com/mikeappsec/lightweightauth/api/proto/lightweightauth/v1;authv1b\x06proto3"

var (
	file_lightweightauth_v1_auth_proto_rawDescOnce sync.Once
	file_lightweightauth_v1_auth_proto_rawDescData []byte
)

func file_lightweightauth_v1_auth_proto_rawDescGZIP() []byte {
	file_lightweightauth_v1_auth_proto_rawDescOnce.Do(func() {
		file_lightweightauth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightweightauth_v1_auth_proto_rawDesc), len(file_lightweightauth_v1_auth_proto_rawDesc)))
	})
	return file_lightweightauth_v1_auth_proto_rawDescData
}

var file_lightweightauth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lightweightauth_v1_auth_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: lightweightauth.v1.AuthorizeRequest
	(*PeerInfo)(nil),          // 1: lightweightauth.v1.PeerInfo
	(*Identity)(nil),          // 2: lightweightauth.v1.Identity
	(*AuthorizeResponse)(nil), // 3: lightweightauth.v1.AuthorizeResponse
	nil,                       // 4: lightweightauth.v1.AuthorizeRequest.HeadersEntry
	nil,                       // 5: lightweightauth.v1.AuthorizeRequest.ContextEntry
	nil,                       // 6: lightweightauth.v1.Identity.ClaimsEntry
	nil,                       // 7: lightweightauth.v1.AuthorizeResponse.UpstreamHeadersEntry
	nil,                       // 8: lightweightauth.v1.AuthorizeResponse.ResponseHeadersEntry
}
var file_lightweightauth_v1_auth_proto_depIdxs = []int32{
	4, // 0: lightweightauth.v1.AuthorizeRequest.headers:type_name -> lightweightauth.v1.AuthorizeRequest.HeadersEntry
	1, // 1: lightweightauth.v1.AuthorizeRequest.peer:type_name -> lightweightauth.v1.PeerInfo
	5, // 2: lightweightauth.v1.AuthorizeRequest.context:type_name -> lightweightauth.v1.AuthorizeRequest.ContextEntry
	6, // 3: lightweightauth.v1.Identity.claims:type_name -> lightweightauth.v1.Identity.ClaimsEntry
	7, // 4: lightweightauth.v1.AuthorizeResponse.upstream_headers:type_name -> lightweightauth.v1.AuthorizeResponse.UpstreamHeadersEntry
	8, // 5: lightweightauth.v1.AuthorizeResponse.response_headers:type_name -> lightweightauth.v1.AuthorizeResponse.ResponseHeadersEntry
	2, // 6: lightweightauth.v1.AuthorizeResponse.identity:type_name -> lightweightauth.v1.Identity
	0, // 7: lightweightauth.v1.Auth.Authorize:input_type -> lightweightauth.v1.AuthorizeRequest
	0, // 8: lightweightauth.v1.Auth.AuthorizeStream:input_type -> lightweightauth.v1.AuthorizeRequest
	3, // 9: lightweightauth.v1.Auth.Authorize:output_type -> lightweightauth.v1.AuthorizeResponse
	3, // 10: lightweightauth.v1.Auth.AuthorizeStream:output_type -> lightweightauth.v1.AuthorizeResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_lightweightauth_v1_auth_proto_init() }
func file_lightweightauth_v1_auth_proto_init() {
	if File_lightweightauth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightweightauth_v1_auth_proto_rawDesc), len(file_lightweightauth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightweightauth_v1_auth_proto_goTypes,
		DependencyIndexes: file_lightweightauth_v1_auth_proto_depIdxs,
		MessageInfos:      file_lightweightauth_v1_auth_proto_msgTypes,
	}.Build()
	File_lightweightauth_v1_auth_proto = out.File
	file_lightweightauth_v1_auth_proto_goTypes = nil
	file_lightweightauth_v1_auth_proto_depIdxs = nil
}
