// Native LightweightAuth gRPC API (Door B in DESIGN.md §1).
//
// This file is the design source of truth for the native authorization
// surface. Code is generated with buf in milestone M2; until then the
// shape is committed here for review.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lightweightauth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_Authorize_FullMethodName       = "/lightweightauth.v1.Auth/Authorize"
	Auth_AuthorizeStream_FullMethodName = "/lightweightauth.v1.Auth/AuthorizeStream"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	// One-shot decision (most common path).
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	// Streaming for long-lived sessions / WebSocket re-checks.
	AuthorizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthorizeRequest, AuthorizeResponse], error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, Auth_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthorizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthorizeRequest, AuthorizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Auth_ServiceDesc.Streams[0], Auth_AuthorizeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuthorizeRequest, AuthorizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auth_AuthorizeStreamClient = grpc.BidiStreamingClient[AuthorizeRequest, AuthorizeResponse]

// AuthServer is the server API for Auth service.
// All implementations should embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	// One-shot decision (most common path).
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	// Streaming for long-lived sessions / WebSocket re-checks.
	AuthorizeStream(grpc.BidiStreamingServer[AuthorizeRequest, AuthorizeResponse]) error
}

// UnimplementedAuthServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAuthServer) AuthorizeStream(grpc.BidiStreamingServer[AuthorizeRequest, AuthorizeResponse]) error {
	return status.Error(codes.Unimplemented, "method AuthorizeStream not implemented")
}
func (UnimplementedAuthServer) testEmbeddedByValue() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call panics, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthorizeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthServer).AuthorizeStream(&grpc.GenericServerStream[AuthorizeRequest, AuthorizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auth_AuthorizeStreamServer = grpc.BidiStreamingServer[AuthorizeRequest, AuthorizeResponse]

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightweightauth.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _Auth_Authorize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuthorizeStream",
			Handler:       _Auth_AuthorizeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lightweightauth/v1/auth.proto",
}
