// ConfigDiscovery — the controller-to-pod push channel that replaces
// ConfigMap+SIGHUP for distributing compiled AuthConfigs. It is the
// transport for `pkg/configstream.Broker`; see docs/DESIGN.md §M11.
//
// Wire shape is deliberately minimal: a single bidi stream where the
// server pushes `Snapshot`s and the client never sends application
// payloads (the open stream itself is the subscription). The version
// field is monotonically increasing per controller so subscribers can
// trivially de-duplicate after a reconnect.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lightweightauth/v1/config_discovery.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamAuthConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id identifies the lwauth pod for log/metrics purposes; it is
	// NOT used for filtering today. Future revisions may use it to
	// route per-node overrides.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAuthConfigRequest) Reset() {
	*x = StreamAuthConfigRequest{}
	mi := &file_lightweightauth_v1_config_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAuthConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAuthConfigRequest) ProtoMessage() {}

func (x *StreamAuthConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_config_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAuthConfigRequest.ProtoReflect.Descriptor instead.
func (*StreamAuthConfigRequest) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_config_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAuthConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AuthConfigSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic per-controller version. Subscribers may use it to
	// de-duplicate across reconnects.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// The compiled AuthConfig spec, encoded as canonical JSON. We use
	// JSON rather than a schemafull message because the spec carries
	// module-specific free-form `config` maps (DESIGN.md §6) that don't
	// round-trip cleanly through protobuf's struct/Any.
	SpecJson      []byte `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfigSnapshot) Reset() {
	*x = AuthConfigSnapshot{}
	mi := &file_lightweightauth_v1_config_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfigSnapshot) ProtoMessage() {}

func (x *AuthConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_lightweightauth_v1_config_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfigSnapshot.ProtoReflect.Descriptor instead.
func (*AuthConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_lightweightauth_v1_config_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *AuthConfigSnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AuthConfigSnapshot) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

var File_lightweightauth_v1_config_discovery_proto protoreflect.FileDescriptor

const file_lightweightauth_v1_config_discovery_proto_rawDesc = "" +
	"\n" +
	")lightweightauth/v1/config_discovery.proto\x12\x12lightweightauth.v1\"2\n" +
	"\x17StreamAuthConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"K\n" +
	"\x12AuthConfigSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\fR\bspecJson2|\n" +
	"\x0fConfigDiscovery\x12i\n" +
	"\x10StreamAuthConfig\x12+.lightweightauth.v1.StreamAuthConfigRequest\x1a&.lightweightauth.v1.AuthConfigSnapshot0\x01BKZIgithub.com/mikeappsec/lightweightauth/api/proto/lightweightauth/v1;authv1b\x06proto3"

var (
	file_lightweightauth_v1_config_discovery_proto_rawDescOnce sync.Once
	file_lightweightauth_v1_config_discovery_proto_rawDescData []byte
)

func file_lightweightauth_v1_config_discovery_proto_rawDescGZIP() []byte {
	file_lightweightauth_v1_config_discovery_proto_rawDescOnce.Do(func() {
		file_lightweightauth_v1_config_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightweightauth_v1_config_discovery_proto_rawDesc), len(file_lightweightauth_v1_config_discovery_proto_rawDesc)))
	})
	return file_lightweightauth_v1_config_discovery_proto_rawDescData
}

var file_lightweightauth_v1_config_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lightweightauth_v1_config_discovery_proto_goTypes = []any{
	(*StreamAuthConfigRequest)(nil), // 0: lightweightauth.v1.StreamAuthConfigRequest
	(*AuthConfigSnapshot)(nil),      // 1: lightweightauth.v1.AuthConfigSnapshot
}
var file_lightweightauth_v1_config_discovery_proto_depIdxs = []int32{
	0, // 0: lightweightauth.v1.ConfigDiscovery.StreamAuthConfig:input_type -> lightweightauth.v1.StreamAuthConfigRequest
	1, // 1: lightweightauth.v1.ConfigDiscovery.StreamAuthConfig:output_type -> lightweightauth.v1.AuthConfigSnapshot
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lightweightauth_v1_config_discovery_proto_init() }
func file_lightweightauth_v1_config_discovery_proto_init() {
	if File_lightweightauth_v1_config_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightweightauth_v1_config_discovery_proto_rawDesc), len(file_lightweightauth_v1_config_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightweightauth_v1_config_discovery_proto_goTypes,
		DependencyIndexes: file_lightweightauth_v1_config_discovery_proto_depIdxs,
		MessageInfos:      file_lightweightauth_v1_config_discovery_proto_msgTypes,
	}.Build()
	File_lightweightauth_v1_config_discovery_proto = out.File
	file_lightweightauth_v1_config_discovery_proto_goTypes = nil
	file_lightweightauth_v1_config_discovery_proto_depIdxs = nil
}
