// ConfigDiscovery — the controller-to-pod push channel that replaces
// ConfigMap+SIGHUP for distributing compiled AuthConfigs. It is the
// transport for `pkg/configstream.Broker`; see docs/DESIGN.md §M11.
//
// Wire shape is deliberately minimal: a single bidi stream where the
// server pushes `Snapshot`s and the client never sends application
// payloads (the open stream itself is the subscription). The version
// field is monotonically increasing per controller so subscribers can
// trivially de-duplicate after a reconnect.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: lightweightauth/v1/config_discovery.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigDiscovery_StreamAuthConfig_FullMethodName = "/lightweightauth.v1.ConfigDiscovery/StreamAuthConfig"
)

// ConfigDiscoveryClient is the client API for ConfigDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigDiscoveryClient interface {
	// Stream the latest AuthConfig snapshot whenever it changes. The
	// server emits the current snapshot (if any) immediately on stream
	// open, then one message per subsequent Publish. Slow consumers get
	// the latest value only — older snapshots are dropped on the server.
	StreamAuthConfig(ctx context.Context, in *StreamAuthConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthConfigSnapshot], error)
}

type configDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigDiscoveryClient(cc grpc.ClientConnInterface) ConfigDiscoveryClient {
	return &configDiscoveryClient{cc}
}

func (c *configDiscoveryClient) StreamAuthConfig(ctx context.Context, in *StreamAuthConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthConfigSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigDiscovery_ServiceDesc.Streams[0], ConfigDiscovery_StreamAuthConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAuthConfigRequest, AuthConfigSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigDiscovery_StreamAuthConfigClient = grpc.ServerStreamingClient[AuthConfigSnapshot]

// ConfigDiscoveryServer is the server API for ConfigDiscovery service.
// All implementations should embed UnimplementedConfigDiscoveryServer
// for forward compatibility.
type ConfigDiscoveryServer interface {
	// Stream the latest AuthConfig snapshot whenever it changes. The
	// server emits the current snapshot (if any) immediately on stream
	// open, then one message per subsequent Publish. Slow consumers get
	// the latest value only — older snapshots are dropped on the server.
	StreamAuthConfig(*StreamAuthConfigRequest, grpc.ServerStreamingServer[AuthConfigSnapshot]) error
}

// UnimplementedConfigDiscoveryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigDiscoveryServer struct{}

func (UnimplementedConfigDiscoveryServer) StreamAuthConfig(*StreamAuthConfigRequest, grpc.ServerStreamingServer[AuthConfigSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamAuthConfig not implemented")
}
func (UnimplementedConfigDiscoveryServer) testEmbeddedByValue() {}

// UnsafeConfigDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigDiscoveryServer will
// result in compilation errors.
type UnsafeConfigDiscoveryServer interface {
	mustEmbedUnimplementedConfigDiscoveryServer()
}

func RegisterConfigDiscoveryServer(s grpc.ServiceRegistrar, srv ConfigDiscoveryServer) {
	// If the following call panics, it indicates UnimplementedConfigDiscoveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigDiscovery_ServiceDesc, srv)
}

func _ConfigDiscovery_StreamAuthConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAuthConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigDiscoveryServer).StreamAuthConfig(m, &grpc.GenericServerStream[StreamAuthConfigRequest, AuthConfigSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigDiscovery_StreamAuthConfigServer = grpc.ServerStreamingServer[AuthConfigSnapshot]

// ConfigDiscovery_ServiceDesc is the grpc.ServiceDesc for ConfigDiscovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigDiscovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightweightauth.v1.ConfigDiscovery",
	HandlerType: (*ConfigDiscoveryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAuthConfig",
			Handler:       _ConfigDiscovery_StreamAuthConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lightweightauth/v1/config_discovery.proto",
}
