controller:
  authConfigName: demo
  enabled: true
  watchNamespace: demo
gateway:
  enabled: true
  service:
    type: NodePort
  upstream:
    port: 8080
    service: backend
image:
  pullPolicy: IfNotPresent
  repository: lwauth
  tag: dev
replicaCount: 1
